using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;

namespace BarberShop
{
    /// <summary>
    /// Interaction logic for FindCustomer.xaml
    /// </summary>
    public partial class FindCustomer : Window
    {
        Controller cont = new Controller();
        private Customer customer;
        public FindCustomer()
        {
            InitializeComponent();

            CustomersView.ItemsSource = cont.GetCustomers();
            CustomersView.AutoGeneratedColumns += CustomersView_AutoGeneratedColumns;
        }

        public Customer GetCustomer()
        {
            return customer;
        }

        private void CustomersView_AutoGeneratedColumns(object sender, EventArgs e)
        {
            CustomersView.Columns[0].Visibility = Visibility.Hidden;
            CustomersView.Columns[4].Visibility = Visibility.Hidden;
        }

        private void btnSelect_Click(object sender, RoutedEventArgs e)
        {
            customer = (Customer)CustomersView.SelectedItem;
            Close();
        }
    }
}
