using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace BarberShop
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        Customer customerNew;
        Customer customerOrder;

        Controller cont = new Controller();
        public MainWindow()
        {
            InitializeComponent();

            UpdateCustomersView();
            UpdateTimeTableView();
            UpdateComboBox();

            CustomersView.AutoGeneratedColumns += CustomersView_AutoGeneratedColumns;
            TimeTableSmall.AutoGeneratedColumns += TimeTableSmall_AutoGenratedColumns;


        }

        private void UpdateComboBox()
        {
            cmbBoxHaircut.ItemsSource = cont.GetHaircuts();
            cmbBoxHaircut.DisplayMemberPath = "name";
        }

        private void UpdateCustomersView()
        {
            CustomersView.ItemsSource = cont.GetCustomers();
        }

        private void UpdateTimeTableView()
        {
            TimeTableSmall.ItemsSource = cont.GetTimeTable();
            TimeTable.ItemsSource = cont.GetTimeTable();
        }

        private void CustomersView_AutoGeneratedColumns(object sender, EventArgs e)
        {
            CustomersView.Columns[0].Visibility = Visibility.Hidden;
            CustomersView.Columns[3].Visibility = Visibility.Hidden;
            CustomersView.Columns[4].Visibility = Visibility.Hidden;
        }

        private void TimeTableSmall_AutoGenratedColumns(object sender, EventArgs e)
        {
            TimeTableSmall.Columns[0].Visibility = Visibility.Hidden;
            TimeTableSmall.Columns[4].Visibility = Visibility.Hidden;
        }

        private void ClearNew_Click(object sender, RoutedEventArgs e)
        {
            TxtBoxCustomerNew.Text = "";
            cmbBoxHaircut.SelectedIndex = -1;
            TxtBoxPriceNew.Text = "";
        }

        private void NewCustomer_Click(object sender, RoutedEventArgs e)
        {
            AddCustomer win = new AddCustomer();
            win.ShowDialog();
            UpdateCustomersView();
            customerNew = win.GetCustomer();

            if (customerNew != null)
                TxtBoxCustomerNew.Text = customerNew.name;
        }

        private void DelCustomerButton_Click(object sender, RoutedEventArgs e)
        { 
            cont.DeleteCustomer((Customer)CustomersView.SelectedItem);
            UpdateCustomersView();
        }

        private void cmbBoxHaircut_SelectionChanged(object sender, SelectionChangedEventArgs e)
        {
            if (cmbBoxHaircut.SelectedIndex != -1)
            {
                TxtBoxPriceNew.Text = ((Haircut)cmbBoxHaircut.SelectedItem).price.ToString();
            }
        }

        private void btnFindCustomer_Click(object sender, RoutedEventArgs e)
        {
            FindCustomer win = new FindCustomer();
            win.ShowDialog();
            UpdateCustomersView();
            customerNew = win.GetCustomer();

            if (customerNew!=null)
                TxtBoxCustomerNew.Text = customerNew.name;

        }

        private void AddNew_Click(object sender, RoutedEventArgs e)
        {

        }
    }
}
