using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace BarberShop
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        Controller cont = new Controller();
        public MainWindow()
        {
            InitializeComponent();
            UpdateCustomersView();
            UpdateTimeTableView();
            CustomersView.AutoGeneratedColumns += CustomersView_AutoGeneratedColumns;
            
        }

        private void UpdateCustomersView()
        {
            CustomersView.ItemsSource = cont.GetCustomers();
        }

        private void UpdateTimeTableView()
        {
            TimeTableSmall.ItemsSource = cont.GetTimeTable();
            TimeTable.ItemsSource = cont.GetTimeTable();
        }

        private void CustomersView_AutoGeneratedColumns(object sender, EventArgs e)
        {
            CustomersView.Columns[0].Visibility = Visibility.Hidden;
            CustomersView.Columns[3].Visibility = Visibility.Hidden;
            CustomersView.Columns[4].Visibility = Visibility.Hidden;
        }

        private void ClearNew_Click(object sender, RoutedEventArgs e)
        {
            TxtBoxCustomerNew.Text = "";
            TxtBoxPriceNew.Text = "";
            txtBoxType.Text = "";
            
        }

        private void AddNew_Click(object sender, RoutedEventArgs e)
        {

        }

        private void NewCustomer_Click(object sender, RoutedEventArgs e)
        {
            TxtBoxCustomerNew.Text = ShowNewCustomerWindow();
        }

        public string ShowNewCustomerWindow()
        {
            AddCustomer win = new AddCustomer();
            win.ShowDialog();
            CustomersView.ItemsSource = cont.GetCustomers();
            return win.GetName();
        }

        private void DelCustomerButton_Click(object sender, RoutedEventArgs e)
        {
            cont.DeleteCustomer((Customer)CustomersView.SelectedItem);
            UpdateCustomersView();
        }
    }
}
