//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarberShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeTable
    {
        public int Id { get; set; }
        public int customer_id { get; set; }
        public System.DateTime date { get; set; }
        public int haricut_id { get; set; }
        public double price { get; set; }
        public System.TimeSpan time { get; set; }
        public int worker_id { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Haircut Haircut { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
