//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarberShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkerHour
    {
        public int Id { get; set; }
        public int worker_id { get; set; }
        public double hours { get; set; }
        public double salary { get; set; }
    
        public virtual Worker Worker { get; set; }
    }
}
